### ISSUE TITLE
Codes to download the videos

### ISSUE THREAD

**Issue by gujiuxiang** [Yugnaynehc/ssta-captioning#1]
Hi could you share with me your trained model?

**Comment by Yugnaynehc** [comment]
Hi gujiuxiang! Sorry for reply late. Unfortunately, the trained model was not maintained. If you want to use the video captioning model, you can try my recent implementation of Hierarchical Boundary-Aware Neural Encoder for Video Captioning (https://github.com/Yugnaynehc/banet). Any suggestion is welcome, thanks!

**Comment by gujiuxiang** [comment]
Very appreciate! Nice project!
