### ISSUE TITLE
Download the paper.

### ISSUE THREAD

**Issue by ahyuan** [Yugnaynehc/ssta-captioning#2]

**Comment by ahyuan** [comment]
Hi， Yugnaynehc. This code is for the paper "Saliency-Based Spatio-Temporal Attention for Video Captioning". How can I get the paper? Thank you very much.

**Comment by Yugnaynehc** [comment]
Hi, ahyuan. This is just a project paper. If you want it, please give me your email address, and I will send you a copy of it.

**Comment by mbajaj01** [comment]
can you also please send this to mohitbajajnsit@gmail.com

**Comment by tuyunbin** [comment]
could you please send your paper to tuyunbin1995@foxmail.com? Thank you very much!

**Comment by AcodeC** [comment]
could you please send your paper to acodec520@gmail.com? Thank you very much!
