### ISSUE TITLE
ImportError: cannot import name feature_h5_lens

### ISSUE THREAD

**Issue by chikiuso** [Yugnaynehc/ssta-captioning#3]
Hi, I got the following error when trying to video.py : 

ImportError: cannot import name feature_h5_lens

Thanks for your help in advance!

**Comment by Yugnaynehc** [comment]
Hi, sorry for replying late! This is a bug there: I do not updated the config file *args.py*, which should be added *feature_h5_lens = 'lens'* at line 86.
